repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-toml

    -   repo: local
        hooks:
        -   id: ruff
            name: ruff
            entry: uv run ruff check
            language: system
            types: [python]
            args: ["--config=pyproject.toml", "--ignore", "E501"]

        -   id: ruff-format
            name: ruff-format
            entry: uv run ruff format
            language: system
            types: [python]

    -   repo: local
        hooks:
          - id: mypy
            name: mypy
            entry: uv run mypy
            language: system
            types: [python]
            require_serial: true
            args: ["--config-file=pyproject.toml"]
            stages: [pre-push]

    - repo: local
      hooks:
          - id: fastapi-root-test
            name: FastAPI Root Endpoint Test
            entry: python -m pytest tests/api/test_root_endpoint.py -v
            language: system
            pass_filenames: false
            types: [python]
            stages: [pre-push]
