services:
  dev:
    build:
      context: .
      target: development
    env_file:
      - .env-dev
    ports:
      - "8888:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - ./logs:/app/logs
    restart: unless-stopped
    command: uv run uvicorn cleansales_backend.api.app:app --host 0.0.0.0 --port 8000 --reload --log-config=/app/src/log_config.json
    # networks:
    #   - supabase-network





  prod:
    build:
      context: .
      target: production
    env_file:
      - .env-prod
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    command: uv run uvicorn cleansales_backend.api.app:app --host 0.0.0.0 --port 8000 --log-config=/app/src/log_config.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"


# networks:
#   supabase-network:
#     name: supabase-network
#     driver: bridge
#     external: true
