services:
  dev:
    build:
      context: .
      target: development
    env_file:
      - .env-dev
    ports:
      - "8888:8001"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - ./logs:/app/logs
    restart: unless-stopped
    command: uv run uvicorn cleansales_backend.api.app:app --host 0.0.0.0 --port 8001 --reload --log-config=/app/src/log_config.json
    # networks:
    #   - supabase_default


  prod:
    build:
      context: .
      target: production
    env_file:
      - .env-prod
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8888:8001"
    restart: unless-stopped
    command: uv run uvicorn cleansales_backend.api.app:app --host 0.0.0.0 --port 8001 --log-config=/app/src/log_config.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    networks:
      - supabase_default

  mono:
    build:
      context: .
      target: production
    env_file:
      - .env-prod
    ports:
      - "8888:8001"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    command: uv run uvicorn cleansales_backend.api.app:app --host 0.0.0.0 --port 8001 --log-config=/app/src/log_config.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    # networks:
    #   - supabase_default



networks:
  supabase_default:
    name: supabase_default
    external: true
