# 使用 Python 3.12 作為基礎映像
FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# 安裝開發工具
# RUN apt-get update && apt-get install -y \
#     git \
#     curl \
#     && rm -rf /var/lib/apt/lists/*

# 複製專案文件

# 設置工作目錄
WORKDIR /app

COPY pyproject.toml README.md .env ./

# 安裝 uv 包管理器
# RUN pip install uv

# 複製依賴文件
# COPY pyproject.toml README.md ./

# 使用 uv 安裝依賴
# RUN uv pip install -e .


# 設置環境變數
# ENV PYTHONPATH=/app/src
# ENV PYTHONUNBUFFERED=1
# ENV ENVIRONMENT=development

# 在容器啟動時運行的命令
# CMD ["python", "src/fastapi/app.py"] 

# RUN uv run cleansales