services:
  dev:
    # image: ghcr.io/gurumfj/cleansales-backend:dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    command: uv run uvicorn src.server.main:app --host 0.0.0.0 --port 8000 --reload --forwarded-allow-ips "*"

  nginx-dev:
    image: nginx:alpine
    ports:
      - "31788:80"
    volumes:
      - ./nginx/fasthtml-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dev
    restart: unless-stopped
               
networks:
  supabase_default:
    name: supabase_default
    external: true
