services:
  cleansales_backend_base:
    build:
      context: .
      target: base
    ports:
      - "8888:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    restart: unless-stopped
    command: uv run uvicorn cleansales_backend.api.app:app --host 0.0.0.0 --port 8000 --reload

  dev:
    extends:
      service: cleansales_backend_base
    build:
      target: development
    env_file:
      - .env-dev

    # develop:
    #   watch:
    #     - action: sync
    #       path: src
    #       target: /app/src

    #     - action: restart
    #       path: src

    #     - action: rebuild
    #       path: ./pyproject.toml

    #     - action: rebuild
    #       path: ./Dockerfile

    #     - action: rebuild
    #       path: ./docker-compose.yml

    #     - action: restart
    #       path: ./pyproject.toml

  prod:
    extends:
      service: cleansales_backend_base
    build:
      target: production
    env_file:
      - .env-prod
