[project]
name = "cleansales-refactor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pierre Wu", email = "gurumfj@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mypy>=1.14.1",
    "pandas>=2.2.3",
    "pydantic>=2.10.6",
    "pandas-stubs>=2.2.0.230",
    "openpyxl>=3.1.5",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "sqlmodel>=0.0.22",
    "fastapi>=0.110.0",
    "uvicorn>=0.28.0",
    "python-multipart>=0.0.9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/cleansales_refactor"]

[tool.pytest.ini_options]
pythonpath = [
    ".",
    "src",
]
testpaths = [
    "tests",
]

[tool.mypy]
python_version = "3.12"
strict = true
exclude = "^.*_.*\\.py$"
explicit_package_bases = true
namespace_packages = true
warn_return_any = true
warn_unused_configs = true
mypy_path = ["src"]
# packages = ["domain", "infrastructure", "shared"]

[[tool.mypy.overrides]]
module = "numpy.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "modules.*"
ignore_missing_imports = false

# [tool.hatch.build.targets.wheel]
# packages = ["src/modules"]

[tool.ruff]
# Enable auto-fix
fix = true
# exclude 731 in ruff
[tool.ruff.lint]  # https://docs.astral.sh/ruff/settings/#lint
ignore = ["E731"]

# # Exclude a variety of commonly ignored directories.
# exclude = [
#     ".bzr",
#     ".direnv",
#     ".eggs",
#     ".git",
#     ".git-rewrite",
#     ".hg",
#     ".mypy_cache",
#     ".nox",
#     ".pants.d",
#     ".pytype",
#     ".ruff_cache",
#     ".svn",
#     ".tox",
#     ".venv",
#     "__pypackages__",
#     "_build",
#     "buck-out",
#     "build",
#     "dist",
#     "node_modules",
#     "venv",
# ]

# # Same as Black.
# line-length = 88
# indent-width = 4

# # Assume Python 3.12
# target-version = "py312"

# [tool.ruff.lint]
# # Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)
# select = [
#     "E",  # pycodestyle errors
#     "F",  # Pyflakes
#     "I",  # isort
#     "N",  # pep8-naming
# ]

# # Allow fix for all enabled rules (when `--fix`) is provided.
# fixable = ["ALL"]

# # Allow unused variables when underscore-prefixed.
# dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
